#!/bin/bash

COMMAND="${1,,}" #first command
OPEN_KONSOLE=false

#command with no arguments
if [ -z "$1" ]; then
    echo
    echo "evil ass rice switcher i made -v" | sed 's/^/  /'
    echo
    echo "c, current                Display the current preset" | sed 's/^/  /'
    echo "i, info <name>            Output the preset's info.txt, defaults to current preset" | sed 's/^/  /'
    echo "l, list [v|vertical]      List available presets" | sed 's/^/  /'
    echo "s, set <name> [-n]        Change the preset" | sed 's/^/  /'
    echo
    echo "-n, --no-konsole          Disable the launching of a new Konsole upon switching" | sed 's/^/  /'
    echo
    exit 1
fi

if [[ "$COMMAND" == "s" || "$COMMAND" == "set" ]]; then

    if [ -z "$2" ]; then
        echo "Usage: rice $COMMAND <name> [-n]"
        exit 1
    fi

    RICE_NAME="${2,,}"

    if [[ "${3,,}" == "-n" || "${3,,}" == "--no-konsole" ]]; then
        OPEN_KONSOLE=false
    else
        OPEN_KONSOLE=true
    fi

    RICE="$HOME/Rices/$RICE_NAME"

    if [ ! -d "$RICE" ]; then
    echo "Rice '$RICE_NAME' does not exist."
    exit 1
    fi

RICES=$( {
    echo "default"
    ls -1 "$HOME/Rices" | grep -iv '^default$' | sort -f
} | sed 's/./\u&/')



#info command
elif [[ "$COMMAND" == "info" || "$COMMAND" == "i" ]]; then

    # No name supplied, use currently active rice
    if [ -z "$2" ]; then
        CURRENT=$(readlink -f "$HOME/.config/fastfetch/config.jsonc")

        if [[ "$CURRENT" == "$HOME/Rices/"* ]]; then
            RICE_NAME=$(echo "$CURRENT" | sed "s|$HOME/Rices/||" | cut -d/ -f1)
        else
            echo "No rice currently selected."
            exit 1
        fi

    # Name supplied, use that rice
    else
        RICE_NAME="${2,,}"
    fi

    RICE="$HOME/Rices/$RICE_NAME"

    if [ ! -d "$RICE" ]; then
        echo "Rice '$RICE_NAME' does not exist."
        exit 1
    fi

    INFO="$RICE/info.md"

    if [ -f "$INFO" ]; then
        glow "$INFO"
    else
        echo "No information available for rice '$RICE_NAME'."
    fi

    exit 0


#current rice
elif [ "$1" = "current" ] || [ "$1" = "c" ] ; then
    CURRENT=$(readlink -f "$HOME/.config/fastfetch/config.jsonc")

    if [[ "$CURRENT" == "$HOME/Rices/"* ]]; then
        RICE_NAME=$(echo "$CURRENT" | sed "s|$HOME/Rices/||" | cut -d/ -f1)
        echo "Current rice: $RICE_NAME"
    else
        echo "No rice currently selected."
    fi

    exit 0


#list of all rices
elif [[ "$COMMAND" == "list" || "$COMMAND" == "l" ]]; then
    RICES=$( {
        echo "default"
        ls -1 "$HOME/Rices" | grep -iv '^default$' | sort -f
    } | sed 's/./\u&/')

    echo
    echo "Available rices:"

    if [[ "${2,,}" == "v" || "${2,,}" == "vertical" ]]; then
        echo "$RICES" | sed 's/^/  /'
    else
        echo "$RICES" | sed ':a;N;$!ba;s/\n/, /g' | sed 's/^/  /'
    fi

    exit 0

else
    echo "Unknown command: $1"
    echo "Use 'rice' for help."
    exit 1
fi


#if it didnt exit by now, confirm a swithc command

echo "Switching to rice: $RICE_NAME"
echo

#------------------------------------------------------

# Fastfetch
if [ -f "$RICE/FastFetch/config.jsonc" ]; then
    mkdir -p "$HOME/.config/fastfetch"

    rm -f "$HOME/.config/fastfetch/config.jsonc"
    rm -f "$HOME/.config/fastfetch/logo.txt"

    ln -sf "$RICE/FastFetch/config.jsonc" \
        "$HOME/.config/fastfetch/config.jsonc"

    if [ -f "$RICE/FastFetch/logo.txt" ]; then
        ln -s "$RICE/FastFetch/logo.txt" \
            "$HOME/.config/fastfetch/logo.txt"
    fi

    echo "✓ Fastfetch   Success"
    else
    echo "✗ Fastfetch   Failed or not found"
fi

# Konsole
if [ -f "$RICE/Konsole/Rice.profile" ]; then
    mkdir -p "$HOME/.local/share/konsole"

    rm -f "$HOME/.local/share/konsole/Rice.profile"

    ln -sf "$RICE/Konsole/Rice.profile" \
        "$HOME/.local/share/konsole/Rice.profile"

    echo "✓ Konsole     Success"
    if $OPEN_KONSOLE; then
    konsole --profile Rice &
    fi
else
    echo "✗ Konsole     Failed or not found"
fi

# Wallpaper
if [ -f "$RICE/Wallpaper/wallpaper.jpg" ]; then
    WALLPAPER="$RICE/Wallpaper/wallpaper.jpg"

    if gdbus call --session \
    --dest org.kde.plasmashell \
    --object-path /PlasmaShell \
    --method org.kde.PlasmaShell.setWallpaper \
    "org.kde.image" \
    "{'Image': <'file://$WALLPAPER'>}" \
    0 >/dev/null; then
    echo "✓ Wallpaper   Success"
    else
    echo "✗ Wallpaper   Failed"
    fi
else
    echo "✗ Wallpaper   Not found, reverting to Default"
    WALLPAPER="$HOME/Rices/default/Wallpaper/wallpaper.jpg"
    gdbus call --session \
    --dest org.kde.plasmashell \
    --object-path /PlasmaShell \
    --method org.kde.PlasmaShell.setWallpaper \
    "org.kde.image" \
   "{'Image': <'file://$WALLPAPER'>}" \
    0 >/dev/null
fi


#------------------------------------------------------

echo
echo "Rice '$RICE_NAME' activated."
    if $OPEN_KONSOLE; then
    echo "A new Konsole window has been opened to display changes."
    fi
